spring.application.name=MyCustomAuthServer
server.port=9000


spring.datasource.url=jdbc:postgresql://localhost:5432/my_auth_server_db
spring.datasource.username=auth_user
spring.datasource.password=auth_password


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true